// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trips.Data.Context;

#nullable disable

namespace Trips.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231101171843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trips.Core.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("PayableTime")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee159f08-4a14-4d69-8f9f-92cebbfbd19c"),
                            Name = "Jack"
                        },
                        new
                        {
                            Id = new Guid("37bd6a0b-d6d6-4525-ac7b-e673717ec8ad"),
                            Name = "Joanne"
                        });
                });

            modelBuilder.Entity("Trips.Core.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("DestinationPlaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartPlaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TripEndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TripStartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1cc80906-88e3-4baf-9855-a4ec131b7307"),
                            DestinationPlaceName = "Place B",
                            DriverId = new Guid("ee159f08-4a14-4d69-8f9f-92cebbfbd19c"),
                            StartPlaceName = "Place A",
                            TripEndTimestamp = new DateTime(2012, 4, 23, 1, 15, 0, 0, DateTimeKind.Utc),
                            TripStartTimestamp = new DateTime(2012, 4, 23, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("84e53efd-a138-4f61-acf4-11de6888475d"),
                            DestinationPlaceName = "Place Bb",
                            DriverId = new Guid("ee159f08-4a14-4d69-8f9f-92cebbfbd19c"),
                            StartPlaceName = "Place Aa",
                            TripEndTimestamp = new DateTime(2012, 4, 23, 2, 2, 0, 0, DateTimeKind.Utc),
                            TripStartTimestamp = new DateTime(2012, 4, 23, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("68e92246-76c9-410b-8f73-dfa62b32edd4"),
                            DestinationPlaceName = "Place B",
                            DriverId = new Guid("ee159f08-4a14-4d69-8f9f-92cebbfbd19c"),
                            StartPlaceName = "Place C",
                            TripEndTimestamp = new DateTime(2012, 4, 23, 3, 47, 0, 0, DateTimeKind.Utc),
                            TripStartTimestamp = new DateTime(2012, 4, 23, 3, 33, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b6bc9b3b-c45e-45ce-94d7-746acdb64f63"),
                            DestinationPlaceName = "Place C",
                            DriverId = new Guid("37bd6a0b-d6d6-4525-ac7b-e673717ec8ad"),
                            StartPlaceName = "Place B",
                            TripEndTimestamp = new DateTime(2012, 4, 23, 1, 22, 0, 0, DateTimeKind.Utc),
                            TripStartTimestamp = new DateTime(2012, 4, 23, 1, 6, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("07e8a2dc-e96b-4f7d-831f-c6cae84edd83"),
                            DestinationPlaceName = "Place B",
                            DriverId = new Guid("37bd6a0b-d6d6-4525-ac7b-e673717ec8ad"),
                            StartPlaceName = "Place C",
                            TripEndTimestamp = new DateTime(2012, 4, 23, 2, 43, 23, 0, DateTimeKind.Utc),
                            TripStartTimestamp = new DateTime(2012, 4, 23, 2, 6, 15, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("94130245-d7d9-4788-a758-77065f1d22d1"),
                            DestinationPlaceName = "Place Bb",
                            DriverId = new Guid("37bd6a0b-d6d6-4525-ac7b-e673717ec8ad"),
                            StartPlaceName = "Place Aa",
                            TripEndTimestamp = new DateTime(2012, 4, 23, 3, 59, 0, 0, DateTimeKind.Utc),
                            TripStartTimestamp = new DateTime(2012, 4, 23, 3, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Trips.Core.Entities.Trip", b =>
                {
                    b.HasOne("Trips.Core.Entities.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Trips.Core.Entities.Driver", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
